/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Userdata;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-30T13:23:07.267Z")

@Api(value = "default", description = "the default API")
@RequestMapping(value = "")
public interface DefaultApi {

    @ApiOperation(value = "", nickname = "getUserdataModel", notes = "", response = Userdata.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful", response = Userdata.class) })
    @RequestMapping(value = "/",
        method = RequestMethod.GET)
    ResponseEntity<Userdata> getUserdataModel();


    @ApiOperation(value = "", nickname = "rootPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful") })
    @RequestMapping(value = "/",
        method = RequestMethod.POST)
    ResponseEntity<Void> rootPost(@ApiParam(value = ""  )  @Valid @RequestBody Userdata userdata);

}
